name       : haskell-base-compat-batteries
version    : 0.11.1
release    : 1
source     :
    - https://hackage.haskell.org/package/base-compat-batteries-0.11.1/base-compat-batteries-0.11.1.tar.gz : caf66fed3c0a3b0437692cad18c93a7074e8524a86b8be1ce04d0a18cbf6aed8
license    : MIT
component  : programming.haskell
summary    : base-compat with extra batteries
description: |
    Provides functions available in later versions of base to a wider range of compilers, without requiring you to use CPP pragmas in your code.
builddeps  :
    - haskell-cabal-install
    - haskell-base-compat-devel
rundeps    :
    - devel:
        - haskell-base-compat-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
